### ISSUE TITLE
Add insertions/frameshifts as branch labels

### ISSUE THREAD

**Issue by corneliusroemer** [neherlab/ncov-simple#5]

**Comment by rneher** [comment]
I added frameshifts and insertions to the metadata in ingest. these should be then part of the metadata once the next ingest has run. The idea would then be to 

 * collect all unique insertions and frameshifts
 * assigned them as a binary characters to leafs
 * do discrete state reconstruction on them (like the traits rule)
 * for each branch, collect the events (separately for insertions and deletions) that map to it
 * construct a label for insertions and deletions that can be displayed on the branch.

**Comment by corneliusroemer** [comment]
Write separate script using Augur ancestral/traits functions as a library.

- Build own characters
- Each unique frameshift/insertion gets a binary trait, binary vector
- Import mugration_inference frequency from Augur
